version: '3.6'

services:
  techdocs:
    image: spotify/techdocs
    command: build
    working_dir: /development
    # Needed for chown of local storage
    volumes:
      - ./:/development
  gitversion:
    image: gittools/gitversion:5.6.6
    working_dir: /repo
    # Needed for chown of local storage
    volumes:
      - ./:/repo
